version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  orign-vllm:
    build:
      context: .
      dockerfile: ./orign/server/backends/vllm/Dockerfile
    platform: linux/amd64
    container_name: orign-vllm
    environment:
      QUEUE_TYPE: "redis"
      REDIS_URL: "redis://redis:6379"
      QUEUE_INPUT_TOPICS: "Qwen/Qwen2.5-0.5B-Instruct"
      QUEUE_GROUP_ID: "test-group"
      HF_MODEL_NAME: "Qwen/Qwen2.5-0.5B-Instruct"
      DEVICE: "cpu"
      DEBUG: "true"
    depends_on:
      - redis
    networks:
      - app-network
    ports:
      - "8080:8080"
    # volumes:
    #   - ./orign:/app/

networks:
  app-network:
    driver: bridge
